### ISSUE TITLE
멋져여 선생님

### ISSUE THREAD

**Issue by jihogrammer** [Kim-Wangyu/younghan_base#1]

**Comment by Kim-Wangyu** [comment]
그저 지호매니저님의 반만이라도 따라가려고 노력중입니다.. ㅎㅎㅎ 저도 노력하면 지호매니저님처럼 멋져질 수 있겠죠 ? ㅎㅎ

**Comment by jihogrammer** [comment]
저도 영한이형 강의 들었었는데, 입문(?)인지 기본(?)인지 헷갈리네요...

- https://github.com/JihoSpring/SpringIntroduction
- https://github.com/JihoSpring/SpringCorePrinciples-Basic

둘 중 하나니까 참고하시면서 같이 리뷰하면 좋을 것 같습니다!
매니저님은 이미 멋지시잖아여🤓

**Comment by Kim-Wangyu** [comment]
오 감사합니다. ㅎㅎ 참고하겠습니다 !🤓

**Comment by jihogrammer** [comment]
😘
